CREATE TABLE players (
	`id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
	`nickname` VARCHAR(255) NOT NULL,
	`discord_id` VARCHAR(20) NOT NULL,
	`mmr` UNSIGNED INT NOT NULL DEFAULT 0,
	`tier` VARCHAR(10) NOT NULL DEFAULT '',
	`admin` TINYINT NOT NULL DEFAULT 0,
	PRIMARY KEY(`id`),
	INDEX `discord_id_idx` (`discord_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE signups (
	`id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;